---
spacetrack_login: your_login_on_spacetrack.org
spacetrack_password: your_password_on_spacetrack.org
platforms:
- NOAA 12
- NOAA 13
- NOAA 14
- NOAA 15
- NOAA 16
- NOAA 17
- NOAA 18
- NOAA 19
- METOP-A
- METOP-B
platforms_ids:
- '29499'
- '38771'
- '21263'
- '22739'
- '23455'
- '25338'
- '26536'
- '27453'
- '28654'
- '33591'
